use std::io::{BufRead, BufReader, Read, Write};
use serialport::SerialPort;

fn main() {
    let flags = flags::Rumbac::from_env_or_exit();

    use flags::RumbacCmd::*;
    match flags.subcommand {
        List(_) => {
            let ports = serialport::available_ports().expect("Failed to read serial ports");
            println!("Found {} serial ports.", ports.len());
            for p in ports {
                println!("port: {p:?}");
            }
        }
        Info(flags::Info { port }) => {
            // TODO: what baudrate to use by default??
            let bauds = 921600u32;
            use core::time::Duration;
            let mut port: Port = serialport::new(port, bauds)
                .timeout(Duration::from_secs(1))
                .open()
                .expect("Failed to open port")
                .into();
            port.write("V#");
            let line = port.readln();
            println!("{}", line);
        }
    }
}

struct Port {
    inner: BufReader<Box<dyn serialport::SerialPort>>,
}

impl From<Box<dyn SerialPort>> for Port {
    fn from(p: Box<dyn SerialPort>) -> Self {
        Self::new(p)
    }
}

impl Port {
    pub fn new(p: Box<dyn SerialPort>) -> Self {
        let inner = BufReader::new(p);
        Self { inner }
    }

    pub fn write(&mut self, s: &str) {
        println!("> {}", s);
        let _ = self.inner.get_mut().write(s.as_bytes()).expect("Failed to write to port");
    }

    pub fn readln(&mut self) -> String {
        let mut line = String::new();
        let _ = self.inner.read_line(&mut line).expect("Failed to read from port");
        print!("< {}", line);
        line
    }
}

mod flags {
    xflags::xflags! {
        src "./src/main.rs"

        cmd rumbac {
            default cmd list { }
            cmd info {
                required -p,--port port: String
            }
        }
    }
    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Rumbac {
        pub subcommand: RumbacCmd,
    }

    #[derive(Debug)]
    pub enum RumbacCmd {
        List(List),
        Info(Info),
    }

    #[derive(Debug)]
    pub struct List;

    #[derive(Debug)]
    pub struct Info {
        pub port: String,
    }

    impl Rumbac {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}
