use serialport::SerialPort;
use std::io::{BufRead, BufReader, Write};
use std::str::FromStr;

fn main() {
    let flags = flags::Rumbac::from_env_or_exit();

    use flags::RumbacCmd::*;
    match flags.subcommand {
        List(_) => {
            let ports = serialport::available_ports().expect("Failed to read serial ports");
            println!("Found {} serial ports.", ports.len());
            for p in ports {
                println!("port: {p:?}");
            }
        }
        Info(flags::Info { port }) => {
            // TODO: what baudrate to use by default??
            // let bauds = 921600u32;
            let bauds = 230400u32;
            use core::time::Duration;
            let mut port: Port = serialport::new(port, bauds)
                .timeout(Duration::from_secs(1))
                .open()
                .expect("Failed to open port")
                .into();

            // TODO: set binary mode

            // "version" info
            port.write("V#");
            let version = port.read_str();
            // parse "version" info
            const FEATS_PREFIX: &str = "[Arduino:";
            const FEATS_SUFFIX: &str = "]";
            let feats_idx =
                version.find(FEATS_PREFIX).expect("No feats prefix found") + FEATS_PREFIX.len();
            let feats = &version[feats_idx..];
            let feats_end = feats.find(FEATS_SUFFIX).expect("No feats end found");
            let feats: Feats = feats[..feats_end].parse().unwrap();
            println!("{feats:?}");

            if feats.identify_chip {
                port.write("I#");
                let ident = port.read_str();
            }
        }
    }
}

struct Port {
    inner: BufReader<Box<dyn serialport::SerialPort>>,
}

impl From<Box<dyn SerialPort>> for Port {
    fn from(p: Box<dyn SerialPort>) -> Self {
        Self::new(p)
    }
}

impl Port {
    pub fn new(p: Box<dyn SerialPort>) -> Self {
        let inner = BufReader::new(p);
        Self { inner }
    }

    pub fn write(&mut self, s: &str) {
        println!("> {}", s);
        let _ = self
            .inner
            .get_mut()
            .write(s.as_bytes())
            .expect("Failed to write to port");
    }

    pub fn read_str(&mut self) -> String {
        let mut buf = Vec::new();
        // let mut line = String::new();
        let _ = self
            .inner
            // .read_line(&mut line)
            .read_until(b'\0', &mut buf)
            .expect("Failed to read from port");
        buf.pop_if(|b| *b == b'\0');
        buf.pop_if(|b| *b == b'\r');
        buf.pop_if(|b| *b == b'\n');
        let line = std::str::from_utf8(&buf).expect("Cannot parse as UTF8");
        println!("< {line}");
        line.into()
    }
}

#[derive(Debug, Default)]
struct Feats {
    pub chip_erase: bool,
    pub write_buffer: bool,
    pub checksum_buffer: bool,
    pub identify_chip: bool,
    pub reset: bool,
}

#[derive(Debug)]
pub struct ParseFeatsError(pub u8);

impl FromStr for Feats {
    type Err = ParseFeatsError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut feats = Self::default();
        for b in s.as_bytes() {
            match b {
                b'I' => feats.identify_chip = true,
                b'K' => feats.reset = true,
                b'X' => feats.chip_erase = true,
                b'Y' => feats.write_buffer = true,
                b'Z' => feats.checksum_buffer = true,
                _ => return Err(ParseFeatsError(*b)),
            }
        }
        Ok(feats)
    }
}

mod flags {
    xflags::xflags! {
        src "./src/main.rs"

        cmd rumbac {
            default cmd list { }
            cmd info {
                required -p,--port port: String
            }
        }
    }
    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Rumbac {
        pub subcommand: RumbacCmd,
    }

    #[derive(Debug)]
    pub enum RumbacCmd {
        List(List),
        Info(Info),
    }

    #[derive(Debug)]
    pub struct List;

    #[derive(Debug)]
    pub struct Info {
        pub port: String,
    }

    impl Rumbac {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}
